version: "3"

services:
  postgres-db-pgadmin:
    image: dpage/pgadmin4:8.3
    hostname: postgres-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.no
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - 8080:80
    networks:
      - backend_network

  postgres-db:
    image: postgres:13.12
    # image: timescale/timescaledb-ha:pg13
    hostname: postgres-db-direct
    user: root
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/dbdata
    volumes:
      - postgres_data:/var/lib/postgresql/data/dbdata
    ports:
      - 5433:5432
    networks:
      - backend_network

  pgbouncer:
    # https://github.com/edoburu/docker-pgbouncer/blob/master/README.md
    image: edoburu/pgbouncer:latest
    hostname: postgres-db
    entrypoint: []
    command: ["sh", "-c", "cp /etc/pgbouncer_temp/* /etc/pgbouncer/ && /entrypoint.sh /usr/bin/pgbouncer /etc/pgbouncer/pgbouncer.ini"]
    environment:
      DB_USER: admin
      DB_PASSWORD: admin
      DB_HOST: postgres-db-direct
      DB_NAME: "*" # All databases
      AUTH_TYPE: scram-sha-256
      POOL_MODE: transaction
      ADMIN_USERS: admin
    ports:
      - 5432:5432
    configs:
      - source: pgbouncer_userlist.txt
        target: /etc/pgbouncer_temp/userlist.txt
    networks:
      - backend_network
    healthcheck:
      test: ['CMD', 'pg_isready', '-h', 'localhost']


networks:
  backend_network:
    external: true

configs:
  pgbouncer_userlist.txt:
    external: true

volumes:
  postgres_data:
    external: true
  pgadmin_data:
    external: true
