apiVersion: v1
entries:
  postgres:
  - apiVersion: v2
    appVersion: "13.12"
    created: "2025-01-28T10:35:21.0983971+01:00"
    description: Postgres helm chart for Kubernetes
    digest: f41946cd9602c8f04b6507bb420b49decb004dd7cf39422495bdc6d007adfb5b
    home: https://github.com/hansehe/postgres-helm
    icon: https://raw.githubusercontent.com/hansehe/postgres-helm/master/helm/postgres.png
    keywords:
    - postgres
    maintainers:
    - email: hans.erik.heggem@gmail.com
      name: hansehe
    name: postgres
    sources:
    - https://github.com/hansehe/postgres-helm
    type: application
    urls:
    - postgres-0.1.0.tgz
    version: 0.1.0
generated: "2025-01-28T10:35:21.096234+01:00"
