{{- if .Values.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pgbouncer.fullname" . }}-configmap
  labels:
    {{- include "pgbouncer.labels" . | nindent 4 }}
data:
  pgbouncer_userlist.txt: |-
    {{- range .Values.config.users }}
    {{ .username | quote }} {{ .password | quote }}
    {{- end }}
  {{- if .Values.config.init.enabled }}
  pgbouncer.ini: |-
    {{- .Values.config.init.content | nindent 4 }}
  {{- end }}
{{- end }}
