{{- if .Values.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pgbouncer.fullname" . }}-configmap
  labels:
    {{- include "pgbouncer.labels" . | nindent 4 }}
data:
  pgbouncer_userlist.txt: |-
    {{- range $key, $value := .Values.config.users }}
    {{ $key | quote }} {{ $value | quote }}
    {{- end }}
{{- end }}
